// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttsqietrzbgrjwskseyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0c3FpZXRyemJncmp3c2tzZXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzEwNTcsImV4cCI6MjA2MTA0NzA1N30.E1-DUzcLIZgb0HOUJEKmvpKGgm9QQIl4ZrjsQOAsIHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);